export const DEFAULT_RESOURCES = [
  {
    title: 'LeetCode',
    url: 'https://leetcode.com/',
    tags: ['LeetCode', 'algorithms', 'data structures', 'interview'],
    reasonTemplate: 'Practice problems aligned to your recent topics and revision items.',
  },
  {
    title: 'Coursera',
    url: 'https://www.coursera.org/',
    tags: ['Coursera', 'learning', 'academics', 'career'],
    reasonTemplate: 'Structured courses that match your current themes and goals.',
  },
  {
    title: 'edX',
    url: 'https://www.edx.org/',
    tags: ['learning', 'academics', 'career'],
    reasonTemplate: 'University-grade courses to go deeper on what you’ve been studying.',
  },
  {
    title: 'Khan Academy',
    url: 'https://www.khanacademy.org/',
    tags: ['learning', 'academics', 'math', 'science'],
    reasonTemplate: 'Clear explanations and practice for foundational topics that show up in your notes.',
  },
  {
    title: 'MIT OpenCourseWare',
    url: 'https://ocw.mit.edu/',
    tags: ['learning', 'academics', 'science', 'engineering'],
    reasonTemplate: 'Free, in-depth materials if you want a rigorous deep dive.',
  },
  {
    title: 'YouTube',
    url: 'https://www.youtube.com/',
    tags: ['YouTube', 'learning', 'tutorials'],
    reasonTemplate: 'Quick, high-signal tutorials can unblock specific concepts you mentioned.',
  },
  {
    title: 'Wikipedia',
    url: 'https://en.wikipedia.org/',
    tags: ['learning', 'research', 'reference'],
    reasonTemplate: 'Good for fast background research on concepts appearing in your reflections.',
  },
  {
    title: 'Google Scholar',
    url: 'https://scholar.google.com/',
    tags: ['research', 'academics', 'papers'],
    reasonTemplate: 'Find credible sources if you’re exploring a topic in depth.',
  },
  {
    title: 'World Health Organization (WHO)',
    url: 'https://www.who.int/',
    tags: ['health', 'wellbeing', 'reference'],
    reasonTemplate: 'Reliable health information if your entries involve wellbeing topics.',
  },
  {
    title: 'Centers for Disease Control and Prevention (CDC)',
    url: 'https://www.cdc.gov/',
    tags: ['health', 'wellbeing', 'reference'],
    reasonTemplate: 'Evidence-based guidance for common health topics mentioned in your logs.',
  },
  {
    title: 'NeetCode Roadmap',
    url: 'https://neetcode.io/',
    tags: ['algorithms', 'data structures', 'leetcode'],
    reasonTemplate: 'Structured patterns/roadmap to improve consistency on core problem types.',
  },
  {
    title: 'GeeksforGeeks',
    url: 'https://www.geeksforgeeks.org/',
    tags: ['GeeksforGeeks', 'algorithms', 'data structures'],
    reasonTemplate: 'Reference explanations for the concepts you’re studying.',
  },
  {
    title: 'CP-Algorithms',
    url: 'https://cp-algorithms.com/',
    tags: ['algorithms', 'graphs', 'dp', 'dijkstra'],
    reasonTemplate: 'Deep dives on competitive programming algorithms you mentioned.',
  },
  {
    title: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/',
    tags: ['freeCodeCamp', 'javascript', 'react', 'backend'],
    reasonTemplate: 'Hands-on practice to reinforce fundamentals and projects.',
  },
  {
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/',
    tags: ['javascript', 'frontend'],
    reasonTemplate: 'High-quality docs for the JS topics appearing in your notes.',
  },
  {
    title: 'React Docs',
    url: 'https://react.dev/',
    tags: ['react', 'frontend'],
    reasonTemplate: 'Strengthen React concepts based on your recent work.',
  },
  {
    title: 'MongoDB University',
    url: 'https://learn.mongodb.com/',
    tags: ['mongodb', 'backend'],
    reasonTemplate: 'Free courses aligned with your MongoDB-related learning entries.',
  },
];
